[project]
name = "qlurkin-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "panflute>=2.3.1",
    "pygments>=2.19.2",
    "typst>=0.13.7",
]
